language: rust
sudo: false
rust:
  - 1.15.0
  - stable
  - beta
  - nightly
notifications:
  irc:
    channels:
      - "chat.freenode.net#coredump"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
