language: rust
sudo: false
rust:
  - nightly
script:
  - cargo test
  - cargo doc --no-deps
notifications:
  irc:
    channels:
      - "chat.freenode.net#coredump"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
after_success:
  - bash scripts/travis-doc-upload.sh
